<?php

namespace App\Http\Controllers;

use App\Models\Barang;
use App\Models\BidBarang;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class BarangController extends Controller
{
    public function index()
    {
        return view('barang.index', [
            'barang' => Barang::all()
        ]);
    }
    public function index2()
    {
        return view('barang.upload');
    }
    public function show($id)
    {
        $detail_barang = Barang::find($id);

        $bid_barang = BidBarang::with('user') // Eager load relasi user
            ->where('id_barang', $id)
            ->orderBy('harga_bid', 'desc')
            ->take(3)
            ->get();

        return view('barang.detail', compact('detail_barang', 'bid_barang'));
    }


    public function store(Request $request)
    {

        // Simpan nama file dalam database
        // dd($request->all());
        $request->validate([
            'nama_barang' => 'required',
            'kategori_barang' => 'required',
            'harga_barang' => 'required',
            'kelipatan' => 'required',
            'tgl_publish' => 'required',
            'tgl_expired' => 'required',
            'durasi' => 'required',
            'foto_barang' => 'required|image', // Validasi untuk file gambar
        ]);

        try {
            if ($request->hasFile('foto_barang')) {
                $file = $request->file('foto_barang');

                // Generate unique filename
                $nama_file = time() . '_' . $file->getClientOriginalName();

                // Store file in specified directory under storage/app/public/img/barang
                $path = $file->storeAs('public/img/barang', $nama_file);

                // Get the public URL to access the stored file
                // Remove 'public/' from the path since 'public/' is already included in the URL generated by asset()
                $url = asset('storage/img/barang/' . $nama_file);

                // Save the file name to the database
                Barang::create([
                    'nama_barang' => $request->nama_barang,
                    'kategori_barang' => $request->kategori_barang,
                    'harga_barang' => $request->harga_barang,
                    'kelipatan' => $request->kelipatan,
                    'tgl_publish' => $request->tgl_publish,
                    'tgl_expired' => $request->tgl_expired,
                    'durasi' => $request->durasi,
                    'foto_barang' => $nama_file,  // Save filename in database
                    // Other fields...
                ]);

                return redirect('/')->with('success', 'Barang berhasil ditambahkan');
            }
        } catch (\Exception $th) {
            return redirect('/upload_barang')->with('gagal', 'Barang gagal ditambahkan');
        }
    }
}
